"""
TSP Script Generator for Cyclic Voltammetry (CV) measurements
Generates Lua scripts for Keithley 2450 TSP execution
"""


class TSPScriptGenerator:
    """
    Generates TSP (Lua) scripts for Cyclic Voltammetry measurements
    Handles 4-vertex sweep: V1 -> V2 -> V3 -> V4 -> V1
    """
    
    @staticmethod
    def generate_cv_sweep_script(v1, v2, v3, v4, points_per_second, current_range, current_limit=0.1):
        """
        Generate Lua script for CV sweep with 4 vertices
        
        Args:
            v1: First voltage vertex (V)
            v2: Second voltage vertex (V)
            v3: Third voltage vertex (V)
            v4: Fourth voltage vertex (V)
            points_per_second: Sampling density (points/sec)
            current_range: Manual current range (A)
            current_limit: Current limit/compliance (A), default 0.1
            
        Returns:
            str: Complete Lua script as string
        """
        # Calculate total path length
        path_segments = [
            abs(v2 - v1),  # V1 -> V2
            abs(v3 - v2),  # V2 -> V3
            abs(v4 - v3),  # V3 -> V4
            abs(v1 - v4)   # V4 -> V1
        ]
        total_path_length = sum(path_segments)
        
        # Calculate total number of points
        # Estimate time: total_path_length / average_sweep_rate
        # For CV, assume average sweep rate of 1 V/s (can be adjusted)
        estimated_time = total_path_length / 1.0  # seconds
        total_points = int(points_per_second * estimated_time)
        
        # Ensure minimum points per segment
        min_points_per_segment = 10
        total_points = max(total_points, min_points_per_segment * 4)
        
        # Calculate points per segment (proportional to segment length)
        points_per_segment = []
        for segment_length in path_segments:
            if total_path_length > 0:
                points = max(min_points_per_segment, 
                            int(total_points * (segment_length / total_path_length)))
            else:
                points = min_points_per_segment
            points_per_segment.append(points)
        
        # Calculate step sizes for each segment
        step_sizes = []
        for i, (segment_length, points) in enumerate(zip(path_segments, points_per_segment)):
            if points > 1:
                step = segment_length / (points - 1)
            else:
                step = 0.0
            step_sizes.append(step)
        
        # Calculate dwell time (time per point)
        dwell_time = 1.0 / points_per_second  # seconds
        
        # Generate Lua script
        script_lines = [
            "-- Cyclic Voltammetry Sweep Script",
            "-- Generated by TSP Script Generator",
            "",
            "-- Reset and clear buffer",
            "reset()",
            "defbuffer1.clear()",
            "",
            "-- Configure SMU for voltage source, current measurement",
            "smu.source.func = smu.FUNC_DC_VOLTAGE",
            "smu.measure.func = smu.FUNC_DC_CURRENT",
            "smu.measure.sense = smu.SENSE_2_WIRE",
            f"smu.measure.range = {current_range}",
            # Set current compliance (limit) correctly for voltage source mode
            # According to 2450 TSP model, the property is smu.source.ilimit.level
            f"smu.source.ilimit.level = {current_limit}",
            "smu.measure.autozero.enable = smu.OFF",
            "",
            "-- Turn output ON",
            "smu.source.output = smu.ON",
            "",
            "-- Sweep: V1 -> V2 -> V3 -> V4 -> V1",
        ]
        
        # Generate sweep code for each segment
        vertices = [v1, v2, v3, v4, v1]  # Include return to V1
        segment_names = ["V1->V2", "V2->V3", "V3->V4", "V4->V1"]
        
        for seg_idx, (start_v, end_v, step_size, points, seg_name) in enumerate(
            zip(vertices[:-1], vertices[1:], step_sizes, points_per_segment, segment_names)
        ):
            script_lines.append(f"-- Segment {seg_idx + 1}: {seg_name}")
            
            if abs(end_v - start_v) < 1e-9:  # Very small difference
                # Single point
                script_lines.append(f"smu.source.voltage.level = {end_v}")
                script_lines.append(f"smu.measure.read(defbuffer1)")
                script_lines.append(f"delay({dwell_time})")
            else:
                # Determine direction
                if end_v > start_v:
                    # Forward sweep
                    script_lines.append(f"for i = 0, {points - 1} do")
                    script_lines.append(f"    voltage = {start_v} + i * {step_size}")
                    script_lines.append(f"    smu.source.voltage.level = voltage")
                    script_lines.append(f"    smu.measure.read(defbuffer1)")
                    script_lines.append(f"    delay({dwell_time})")
                    script_lines.append("end")
                else:
                    # Reverse sweep
                    script_lines.append(f"for i = 0, {points - 1} do")
                    script_lines.append(f"    voltage = {start_v} - i * {abs(step_size)}")
                    script_lines.append(f"    smu.source.voltage.level = voltage")
                    script_lines.append(f"    smu.measure.read(defbuffer1)")
                    script_lines.append(f"    delay({dwell_time})")
                    script_lines.append("end")
            
            script_lines.append("")
        
        # Finalize script
        script_lines.extend([
            "-- Turn output OFF",
            "smu.source.output = smu.OFF",
            "",
            "-- Wait for completion",
            "waitcomplete()",
            ""
        ])
        
        return "\n".join(script_lines)
    
    @staticmethod
    def calculate_sweep_parameters(v1, v2, v3, v4, points_per_second):
        """
        Calculate sweep parameters without generating script
        Useful for validation and preview
        
        Args:
            v1, v2, v3, v4: Voltage vertices (V)
            points_per_second: Sampling density (points/sec)
            
        Returns:
            dict: Dictionary with calculated parameters
        """
        path_segments = [
            abs(v2 - v1),
            abs(v3 - v2),
            abs(v4 - v3),
            abs(v1 - v4)
        ]
        total_path_length = sum(path_segments)
        
        estimated_time = total_path_length / 1.0  # seconds
        total_points = int(points_per_second * estimated_time)
        total_points = max(total_points, 40)  # Minimum 40 points (10 per segment)
        
        return {
            'total_path_length': total_path_length,
            'estimated_time': estimated_time,
            'total_points': total_points,
            'segment_lengths': path_segments
        }

